<a href="https://colab.research.google.com/github/GeorgeLucas1/estudo-analise-de-dados-1/blob/main/estudando1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROJETO DE ESTUDOS DE ANÁLISE DE DADOS CSV**

![transferir.jpeg]()

**olá,meu nome é George lucas,sou estudante  nesse mini projeto  notebook irei analisar os dados de consumo combustivel de um dataset disponibilizado pelo kaggle pelo link:**
https://www.kaggle.com/datasets/tanishqdublish/vehcile-fuel-consumption

estarei importando algumas bibliotecas importante no desenvolvimento desse projeto.

**importando bibliotecas:**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

Mounted at /content/drive/

**importando CSV e fazendo as primeira linhas**

In [ ]:
Projeto_ConsumoCombustivel= pd.read_csv('/content/drive/My Drive/fuel.csv',low_memory=False)
Projeto_ConsumoCombustivel.head()

,vehicle_id,year,make,model,class,drive,transmission,transmission_type,engine_index,engine_descriptor,...,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,range_ft2,city_range_ft2,highway_range_ft2
0,26587,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9001,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
1,27705,1984,Alfa Romeo,GT V6 2.5,Minicompact Cars,NaN,Manual 5-Speed,NaN,9005,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
2,26561,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9002,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
3,27681,1984,Alfa Romeo,Spider Veloce 2000,Two Seaters,NaN,Manual 5-Speed,NaN,9006,(FFS) CA model,...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0
4,27550,1984,AM General,DJ Po Vehicle 2WD,Special Purpose Vehicle 2WD,2-Wheel Drive,Automatic 3-Speed,NaN,1830,(FFS),...,0.0,0,0,0,0,0.0,0.0,NaN,0.0,0.0

 análise exploratória de dados , do inglês Exploratory Data Analysis , é uma técnica usada em estatística e ciência de dados para se ter uma primeira ideia de sua base. Na prática, é como dar uma espiada rápida em seus dados para saber do que eles se tratam antes de fazer análise mais elaboradas
 Apartir de agora estarei ultilizando ferramentas das bibilioteca importada para realização dessa análise.

In [ ]:
Projeto_ConsumoCombustivel.describe()

,vehicle_id,year,engine_index,engine_cylinders,engine_displacement,supercharger,fuel_type_2,city_mpg_ft1,unrounded_city_mpg_ft1,city_mpg_ft2,...,hours_to_charge_ac_240v,composite_city_mpg,composite_highway_mpg,composite_combined_mpg,range_ft1,city_range_ft1,highway_range_ft1,range_ft2,city_range_ft2,highway_range_ft2
count,38113.000000,38113.000000,38113.000000,37977.000000,37979.000000,0.0,0.0,38113.000000,38113.000000,38113.000000,...,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,38113.000000,0.0,38113.000000,38113.000000
mean,19170.638496,2000.194527,8799.389001,5.736656,3.317583,NaN,NaN,17.981109,4.606426,0.546218,...,0.005549,0.082203,0.080891,0.081311,0.469708,0.426249,0.419197,NaN,0.043973,0.040051
std,11134.878665,10.464573,17781.058490,1.752254,1.361995,NaN,NaN,6.849728,10.113963,4.109282,...,0.161014,2.156682,2.052187,2.097794,9.352069,9.104702,9.315914,NaN,1.311628,1.169281
min,1.000000,1984.000000,0.000000,2.000000,0.000000,NaN,NaN,6.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
25%,9529.000000,1991.000000,0.000000,4.000000,2.200000,NaN,NaN,15.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
50%,19058.000000,2001.000000,212.000000,6.000000,3.000000,NaN,NaN,17.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
75%,28779.000000,2009.000000,4451.000000,6.000000,4.300000,NaN,NaN,20.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.000000
max,38542.000000,2017.000000,69102.000000,16.000000,8.400000,NaN,NaN,150.000000,150.000000,145.000000,...,7.000000,97.000000,81.000000,88.000000,315.000000,305.900000,346.900000,NaN,103.030000,90.550000

significado dos termo gerado usando .describe
_________________________
count=quantidade

mean=média

min=minimo

std=variancia padrão

25%=primeiro quartil

50%=segundo quartil

75%=terceiro quartil

max=valor máximo
________________________________

No código abaixo, podemos identificar o tipo do valor do o, seja ele Int, Float ou objeto, utilizando o atributo info.

In [ ]:
Projeto_ConsumoCombustivel.info()

#retorna os valores nulos de cada  coluna:

In [ ]:
Projeto_ConsumoCombustivel.isnull().sum()

vehicle_id               0
year                     0
make                     0
model                    0
class                    0
                     ...
city_range_ft1           0
highway_range_ft1        0
range_ft2            38113
city_range_ft2           0
highway_range_ft2        0
Length: 81, dtype: int64

#forma do conjunto de dados

In [ ]:
Projeto_ConsumoCombustivel.shape

(38113, 81)

#tipos de transmisão

#Carros por ano

In [ ]:
Projeto_ConsumoCombustivel['year'].unique()

array([1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994,
       1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005,
       2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
       2017])

#todos os carros presentes

In [ ]:
Projeto_ConsumoCombustivel['model'].value_counts().reset_index().head(30)

                   index  model
0        F150 Pickup 2WD    209
1              Truck 2WD    187
2        F150 Pickup 4WD    187
3                Mustang    184
4                  Jetta    172
5      Ranger Pickup 2WD    169
6                 Camaro    166
7                  Civic    152
8        Sierra 1500 4WD    149
9        Sierra 1500 2WD    149
10                Accord    147
11               Eclipse    133
12                 Camry    123
13               Corolla    123
14                Sentra    120
15        S10 Pickup 2WD    118
16     Ranger Pickup 4WD    113
17             Truck 4WD    113
18  D100/D150 Pickup 2WD    112
19     Dakota Pickup 2WD    108
20                  Colt    107
21       F250 Pickup 2WD    106
22      C1500 Pickup 2WD    106
23    E150 Econoline 2WD    105
24      K1500 Pickup 4WD    101
25              Cavalier    101
26                Lancer    100
27   Ram 1500 Pickup 2WD     98
28        G10/20 Van 2WD     96
29            Tacoma 2WD     96